[package]
name = "boogameow/partner"
description = "Basic global matchmaking for story intersections"
version = "0.1.1"
license = "MIT"
authors = ["boogameow"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
